#!/bin/bash

#SBATCH --job-name="GALT-simulation"
#SBATCH --nodes=9
#SBATCH --ntasks-per-node=16
#SBATCH --ntasks=144
#SBATCH --time=00:59:00
#SBATCH --exclusive
#SBATCH -o stdout
#SBATCH -e stderr
#SBATCH --export=ALL
#SBATCH --mail-type=ALL
#SBATCH --mail-user=bfuller@mines.edu

cd ~/bins/Gut-Associated-Lymphoid-Tissue-Simulation/

export OMP_NUM_THREADS=16
srun --kill-on-bad-exit=1 -n 9 ./sim_hybrid Scaling.conf 3 3
