#!/bin/bash

#SBATCH --job-name="GALT-simulation"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:59:00
#SBATCH --exclusive
#SBATCH -o stdout.1
#SBATCH -e stderr.1
#SBATCH --export=ALL
#SBATCH --mail-type=ALL
#SBATCH --mail-user=bfuller@mines.edu

cd ~/bins/Gut-Associated-Lymphoid-Tissue-Simulation/

export OMP_NUM_THREADS=1
srun --kill-on-bad-exit=1 -n 1 ./sim_hybrid Scaling.conf 1 1
