#!/bin/bash

#SBATCH --job-name="GALT-simulation"
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=12
#SBATCH --time=00:59:00
#SBATCH --exclusive
#SBATCH -o stdout
#SBATCH -e stderr
#SBATCH --export=ALL
#SBATCH --mail-type=ALL
#SBATCH --mail-user=bfuller@mines.edu
#You can change this to your email, but I won't mind being automaticially told when you're grading this

cd ~/bins/Gut-Associated-Lymphoid-Tissue-Simulation/

export OMP_NUM_THREADS=12
srun --kill-on-bad-exit=1 -n 4 ./sim_hybrid Scaling.conf 2 2
